name: awesome_flutter_layouts
description: A list of awesome latyout built in flutter.

version: 1.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  shaders:
    - assets/shaders/shader.frag
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/clock_demo/
